version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "33306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    networks:
      blog-network:
        aliases:
          - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourPassword
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=yourPassword
    volumes:
      - ./mysql/data/:/var/lib/mysql
  nginx:
    image: nginx:1.14-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      blog-network:
        aliases:
          - nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl/blog
      - ./nginx/log:/var/log/nginx
  ghost:
    image: ghost:2.15-alpine
    depends_on:
      - mysql
      - nginx
    expose:
      - "2368"
    volumes:
      - ./ghost/config/config.json:/var/lib/ghost/config.production.json
      - ./ghost/content:/var/lib/ghost/content
    networks:
      blog-network:
        aliases:
          - ghost
networks:
  blog-network:
    driver: bridge
